# -*- coding: utf-8 -*-
"""crime data1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10tqZtGCSDxpXrZFOTpNF3gAPLL4iwmKT
"""

!pip install pandas numpy matplotlib seaborn folium scikit-learn
from google.colab import files
uploaded = files.upload()

# Install required libraries
!pip install folium

# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import folium
from folium.plugins import HeatMap

# Load the dataset
df = pd.read_csv('Crime_Data_from_2020_to_Present.csv')

# Display the first few rows
df.head()

# Check for missing values
df.isnull().sum()

# Get dataset information
df.info()

# Convert 'DATE OCC' to datetime format
df['DATE OCC'] = pd.to_datetime(df['DATE OCC'], errors='coerce')

# Drop rows with missing 'DATE OCC'
df = df.dropna(subset=['DATE OCC'])

# Extract year and month from 'DATE OCC'
df['Year'] = df['DATE OCC'].dt.year
df['Month'] = df['DATE OCC'].dt.month

# Drop rows with missing latitude or longitude
df = df.dropna(subset=['LAT', 'LON'])

# Plot number of crimes per year
plt.figure(figsize=(12,6))
sns.countplot(x='Year', data=df, palette='viridis')
plt.title('Number of Crimes per Year')
plt.xticks(rotation=45)
plt.xlabel('Year')
plt.ylabel('Number of Crimes')
plt.tight_layout()
plt.show()

# Plot number of crimes per month
plt.figure(figsize=(12,6))
sns.countplot(x='Month', data=df, palette='magma')
plt.title('Number of Crimes per Month')
plt.xlabel('Month')
plt.ylabel('Number of Crimes')
plt.tight_layout()
plt.show()

# Create a base map
la_map = folium.Map(location=[34.0522, -118.2437], zoom_start=10)

# Prepare data for heatmap
heat_data = [[row['LAT'], row['LON']] for index, row in df.iterrows()]

# Add heatmap layer
HeatMap(heat_data).add_to(la_map)

# Display the map
la_map

